// frontend/hands-on07/student-portal-angular/src/app/course-card/course-card.component.ts
import { Component, Input } from '@angular/core';

// Task 1, step 92: @Input() properties passed down from CourseListComponent.
@Component({
  selector: 'app-course-card',
  templateUrl: './course-card.component.html',
  styleUrls: ['./course-card.component.css']
})
export class CourseCardComponent {
  @Input() name = '';
  @Input() code = '';
  @Input() credits = 0;
  @Input() grade = '';
}

<article class="course-card">
  <h3>{{ name }}</h3>
  <p>{{ code }} &mdash; {{ credits }} credits</p>
  <span>Grade: {{ grade }}</span>
</article>

// frontend/hands-on5/student-portal-react/src/components/Coursecard.jsx
function CourseCard({ id, name, code, credits, grade, onEnroll }) {
  return (
    <article className="course-card">
      <h3>{name}</h3>
      <p>{code}</p>
      <span>{credits} credits</span>
      <p className="grade">Grade: {grade}</p>
      <button onClick={() => onEnroll({ id, name, code, credits, grade })}>
        Enroll
      </button>
    </article>
  );
}

export default CourseCard;
